apiVersion: v1
kind: Service
metadata:
  name: elastic-ml-worker
spec:
  selector:
    app: elastic-ml-worker
  clusterIP: None
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: elastic-ml-worker
  labels:
    k8s-app: elastic-ml-worker
spec:
  replicas: 16
  selector:
    matchLabels:
      app: elastic-ml-worker
  template:
    metadata:
      labels:
        app: elastic-ml-worker
    spec:
      serviceAccountName: default
      containers:
      - name: elastic-ml-worker
        image: us-west1-docker.pkg.dev/ml-elasticity/elastic-ml/varuna
        imagePullPolicy: Always
        workingDir: /workspace
        command: [ "sleep" ]
        args: [ "infinity" ]
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
